accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

editor/urls.py
from django.urls import path
from . import views

app_name = 'editor'

urlpatterns = [
    path('', views.home, name="home"),
    path('code/<str:unique_code_id>/', views.get_code_view, name='get_code_view'),
    path('submit/', views.submit, name="submit"),
    path('fetch_question/', views.fetch_question, name="fetch_question"),
    path('share/', views.share, name="share"),
    path('show/', views.show, name="show"),
    path('tempEdit/', views.edit_temp, name="tempEdit"),
    path('send_message/', views.send_message, name="send_message"),
    path('delete_message/', views.delete_message, name="send_message"),
]

profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'
urlpatterns = [
    path('<str:username>/', views.profile_view, name='profile'),
    path('send_friend_request/<str:friend_username>/', views.send_friend_request_view, name='send_friend_request'),
    path('accept_friend_request/<int:friend_request_id>/', views.accept_friend_request_view,
         name='accept_friend_request'),
    path('follow_user/<str:user_name>/', views.follow_user, name='follow_user'),
]

the_code_provider/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('accounts/', include('accounts.urls')),
    path('code_editor/', include('editor.urls'), name="code_editor"),
    path('profile/', include('profiles.urls')),
    path('shared/', include('SharedCode.urls')),
    path('userCodes/', include('userCodes.urls')),
]

the_code_provider/views.py
from django.shortcuts import render
from django.http import HttpResponse


def home(request):
    context = {
        "title": "home"
    }
    return render(request, 'the_code_provider/index.html', context)

templates/the_code_provider/basic.html
<!-- this template will be used for template inheritance -->

{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'styles/bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'styles/dashboard/style.css' %}">
    <link rel="icon" href="{% static 'icons/favicon.svg' %}">


    <!-- here css will come -->
    {% block css %}{% endblock %}

    <!-- here heading will come -->
    <title>{% block title %}{% endblock %}</title>
</head>

<body>

    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
        <span>
            <div class="navbar-brand col-md-3 col-lg-2 mr-0 px-3">
                <img src="{% static 'icons/menu.svg' %}" alt="menu" style="height: 1rem; margin: 0 5px;" id="menu">
                <a href="/"> <img src="{% static 'images/logo.png' %}" alt="CPLover" style="height: 1.7rem;"> </a>
            </div>
        </span>
        <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse"
            data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search"
            style="margin: 0 15px;">
    </nav>

    <div class="container-fluid">
        <div class="row" id="dashboard">
            <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
                <div class="sidebar-sticky pt-3">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active" href="#">
                                Dashboard <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{%url 'home' %}">
                                Home
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{%url 'editor:home' %}">
                                Editor
                            </a>
                        </li>
                    </ul>
                    <ul class="nav flex-column mb-2">
                        {%if not user.is_authenticated%}
                            <li class="nav-item">
                                <a class="nav-link" href="{%url 'accounts:login' %}">
                                    Login
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{%url 'accounts:signup' %}">
                                    SignUp
                                </a>
                            </li>
                        {%else%}
                             <li class="nav-item">
                                <a class="nav-link" href="{%url 'profiles:profile' user.username%}">
                                    Profile
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{%url 'accounts:logout' %}">
                                    Logout
                                </a>
                            </li>
                        {%endif%}
                    </ul>
                </div>
            </nav>

        </div>
        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4" id="content_container">

            <!-- here body will come -->
            {% block body %}{% endblock %}
            
            <!-- footer -->
            <!-- Site footer -->
            <footer class="site-footer" style="margin-top: 100px;">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-12 col-md-6">
                            <h6>About</h6>
                            <p class="text-justify"> <i>CODE WANTS TO BE SIMPLE </i> is an initiative to
                                help the upcoming programmers with the code. Scanfcode focuses on providing the most
                                efficient code or snippets as the code wants to be simple. We will help programmers
                                build up concepts in different programming languages that include C, C++, Java, HTML,
                                CSS, Bootstrap, JavaScript, PHP, Android, SQL and Algorithm.</p>
                        </div>

                        <div class="col-xs-6 col-md-3">
                            <h6>Categories</h6>
                            <ul class="footer-links">
                                <li><a href="javascript:void(0);">C</a></li>
                                <li><a href="javascript:void(0);">UI Design</a></li>
                                <li><a href="javascript:void(0);">PHP</a></li>
                                <li><a href="javascript:void(0);">Java</a></li>
                                <li><a href="javascript:void(0);">Android</a></li>
                                <li><a href="javascript:void(0);">Templates</a></li>
                            </ul>
                        </div>

                        <div class="col-xs-6 col-md-3">
                            <h6>Quick Links</h6>
                            <ul class="footer-links">
                                <li><a href="javascript:void(0);">About Us</a></li>
                                <li><a href="javascript:void(0);">Contact Us</a></li>
                                <li><a href="javascript:void(0);">Contribute</a></li>
                                <li><a href="javascript:void(0);">Privacy Policy</a></li>
                                <li><a href="javascript:void(0);">Sitemap</a></li>
                            </ul>
                        </div>
                    </div>
                    <hr>
                </div>
                <div class="container">
                    <div class="row">
                        <div class="col-md-8 col-sm-6 col-xs-12">
                            <p class="copyright-text">Copyright &copy; 2020 All Rights Reserved developed by <a href="javascript:void(0);">Prince</a> And
                                <a href="javascript:void(0);">Udit</a>.
                            </p>
                        </div>

                        <div class="col-md-4 col-sm-6 col-xs-12">
                            <ul class="social-icons">
                                <li><a class="facebook" href="javascript:void(0);"><i class="fa fa-facebook"></i></a></li>
                                <li><a class="twitter" href="javascript:void(0);"><i class="fa fa-twitter"></i></a></li>
                                <li><a class="dribbble" href="javascript:void(0);"><i class="fa fa-dribbble"></i></a></li>
                                <li><a class="linkedin" href="javascript:void(0);"><i class="fa fa-linkedin"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </footer>
        </main>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->

    <!-- here script will come -->
    <script src="{% static 'js/bootstrap/jquery-3.5.1.slim.min.js' %}"></script>
    <script src="{% static 'js/bootstrap/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bootstrap/jquery.min.js' %}"></script>
    <script src="{% static 'js/dashboard/script.js' %}"></script>
    {% block script %} {% endblock %}
</body>

</html>

templates/the_code_provider/code_editor.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'styles/bootstrap.min.css' %}">

    <title>{{title}}</title>

    <style>
        #editor {
            position: relative;
            top: 0px;
            left: 0px;
            height: 35rem;
            width: 100%;
            font-size: 1rem;
            margin-bottom: 2rem;
        }
    </style>
    
  </head>
  <body>
    
    <div id="editor" class="mb-4">
        print("prince is a good boy")
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'js/bootstrap/jquery-3.5.1.slim.min.js' %}"></script>
    <script src="{% static 'js/bootstrap/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/editor/ace.js' %}"></script>
    <script>
        var editor = ace.edit("editor");
        editor.setReadOnly(false);
        editor.autoIndent(false);
        editor.setTheme("ace/theme/dracula");
        const nmode = "ace/mode/python";
        editor.session.setMode(nmode);
    </script>
  </body>
</html>

templates/the_code_provider/index.html
{% extends 'the_code_provider/basic.html' %}

<!-- loaded static -->
{% load static %}

{% block title %}{{title}}{% endblock %}

{% block css %}{% endblock %}

{% block body%}
<h3 class="text-center" style="color: rgb(94, 138, 219); margin: 50px 0;">WEBSITES WITH US</h3>

<div class="card-deck">
    <div class="col-md-3 my-5">
        <div class="card" style="border: none;">
            <a href="javascript:void(0);"><img src="{% static 'images/codeforces.png' %}" class="card-img-top" alt="..."
                    style="height: 16rem"></a>
        </div>
    </div>
    <div class="col-md-3 my-5">
        <div class="card" style="border: none;">
            <a href="javascript:void(0);"><img src="{% static 'images/leetcode.png' %}" class="card-img-top" alt="..."
                    style="height: 16rem"></a>
        </div>
    </div>
    <div class="col-md-3 my-5">
        <div class="card" style="border: none;">
            <a href="javascript:void(0);"><img src="{% static 'images/codechef.png' %}" class="card-img-top" alt="..."
                    style="height: 16rem"></a>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}{% endblock %}